import {Inter, Domine, Orbitron} from "next/font/google"
import "./globals.css"

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
})

const domine = Domine({
  variable: "--font-domine",
  subsets: ["latin"],
})

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
})

export const metadata = {
  title: "Moneda",
  description: "Generated by create next app",
}

export default function RootLayout({children}) {
  return (
    <html lang="es">
      <body
        className={`${inter.variable} ${domine.variable} ${orbitron.variable} antialiased volumecontrol-initialized`}
      >
        {children}
      </body>
    </html>
  )
}
